name: Setup Dependencies
description: Setup dependencies for node
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - run: npm ci
      shell: bash
