name: Setup Dependencies
description: Setup dependencies for node
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: ls -lha
    - uses: actions/setup-node@v2
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci
      shell: bash
