name: Setup Dependencies
description: Setup dependencies for node
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 20
        cache: 'npm'
      working-directory: frontend
    - run: npm ci
      shell: bash
      working-directory: frontend
