name: 'CI'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -lha
        shell: bash
      - uses: ./.github/actions/setup
      - name: 'Prettier check'
        run: npx prettier --check .
      - name: 'Prettier check astro'
        run: npx prettier --check ./**/*.astro
      - name: 'Eslint check'
        run: npx eslint .
      - name: 'Style check'
        run: npx stylelint "**/*.{astro,scss}"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: npm run build
