name: 'CI'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: 'Prettier check'
        run: npx prettier --check .
        working-directory: frontend
      - name: 'Prettier check astro'
        run: npx prettier --check ./**/*.astro
        working-directory: frontend
      - name: 'Eslint check'
        run: npx eslint .
        working-directory: frontend
      - name: 'Style check'
        run: npx stylelint "**/*.{astro,scss}"
        working-directory: frontend
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: npm run build
        working-directory: frontend
