name: 'CI'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: 'Prettier check'
        run: cd frontend && npx prettier --check .
      - name: 'Prettier check astro'
        run: cd frontend && npx prettier --check ./**/*.astro
      - name: 'Eslint check'
        run: cd frontend && npx eslint .
      - name: 'Style check'
        run: cd frontend && npx stylelint "**/*.{astro,scss}"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: cd frontend && npm run build
