name: 'CI'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
  test:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
